"""Write the vectors the client's Dart track maths is pinned to (issue #366).

The client edits and splits an end-to-end-encrypted activity's track on the
device, so it carries a Dart port (``flutter_client/lib/src/track_metrics/``)
of the server's track maths. Python is the source of truth: this script runs
the Python functions over a fixed set of inputs and writes what they return to
``flutter_client/test/fixtures/track_metrics_vectors.json``. The Dart tests
assert the port reproduces every vector; ``tests/test_track_metrics_parity.py``
fails when the committed file no longer matches what this script produces.

Run from the repo root after changing any of the functions below, and commit
the result::

    python scripts/gen_track_metrics_vectors.py

For a Dart implementer — the file, without reading any Python:

* The top level holds ``_schema`` (these notes, condensed), ``constants`` (the
  Python constants by their Python names) and one section per function. A
  section is a list of cases ``{"name", "input", "expected"}``; ``name`` says
  what the case exercises. A case expected to raise has ``"expected_error"``
  instead of ``"expected"``.
* Floats are compared within 1e-6; ints, strings, booleans and nulls exactly.
  A field documented as int is written without a decimal point; every other
  number is a double even when it looks integral (``100.0``).
* A point is ``[lat, lng, elev]``, ``elev`` null when missing. A raw input
  elevation that is not finite or lies outside [-20000, 20000] m is treated as
  missing when the point is built (Python ``TrackPoint.__post_init__``); the
  vectors carry ``65535`` and ``-25000`` for that, JSON having no NaN.
* Python semantics a port must mirror exactly are listed in ``_SCHEMA`` below.

Deterministic: every random series comes from ``tests/elevation_bench`` with a
fixed seed and is rounded (Python's correctly-rounded ``round``) before use, so
the inputs are exact decimals whatever the platform's libm.
"""
from __future__ import annotations

import json
import math
import os
import sys
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from src.models import track_edit as te  # noqa: E402 — after the sys.path fix
from src.models.great_circle import haversine_km  # noqa: E402
from tests.elevation_bench import generators as gen  # noqa: E402

OUTPUT = _ROOT / "flutter_client" / "test" / "fixtures" / "track_metrics_vectors.json"

_SCHEMA = [
    "Generated by scripts/gen_track_metrics_vectors.py from the Python track maths "
    "(src/models/track_edit.py, src/models/great_circle.py, _apportion_gain in "
    "src/project/repo_activities.py, the 'polyline' package). Do not edit by hand.",
    "Each section is a list of {name, input, expected}; a case that must raise has "
    "expected_error (the Python exception name) instead of expected.",
    "Compare floats within 1e-6; ints, strings, booleans and nulls exactly. Fields "
    "documented as int are written without a decimal point; all other numbers are doubles.",
    "A point is [lat, lng, elev]; elev null = missing. A raw elevation outside "
    "[-20000, 20000] (or not finite) becomes null when the point is built, before any "
    "maths: the inputs use 65535 and -25000 for that.",
    "haversine_km: input {lat1, lng1, lat2, lng2} degrees -> km, R = 6371.0.",
    "polyline_encode: input {points: [[lat, lng], ...]} -> Google polyline, precision 5; "
    "null for no points (points_to_polyline). Each coordinate is scaled by 100000 and "
    "rounded HALF AWAY FROM ZERO (Dart's num.round), then delta-encoded.",
    "align_points: input {summary_polyline: string|null, elevation_profile: "
    "{distances_km, elevations_m}|null} -> list of points. Elevation is interpolated "
    "by cumulative haversine distance along the decoded polyline, bisect_left over "
    "distances_km; before the first / past the last sample takes that sample. A missing, "
    "empty or length-mismatched profile gives every point elev null.",
    "points_to_elevation_profile: input {points} -> {distances_km, elevations_m} or "
    "null when there are no points or no point has an elevation.",
    "interpolate_elevation_gaps: input {distances_km, elevations (null = hole)} -> "
    "filled list. Leading/trailing holes take the nearest known value; interior holes "
    "are linear by distance, 0.0 fraction when the bracketing distances are equal.",
    "run_stride: input {elevations} -> int. noise_estimate: input {elevations} -> "
    "{sigma: double, stride: int}. smooth_elevations: input {elevations, distances_km|null, "
    "sigma, stride: int} -> {smoothed, window}. noise_threshold: input {sigma, stride: int, "
    "window} -> double. These are elevation_gain's private helpers (_run_stride, "
    "_noise_estimate, _smooth_elevations, _noise_threshold).",
    "elevation_gain: input {elevations, distances_km|null} -> expected double; "
    "'diagnostics' {sigma, stride, window, threshold} are the helper values on the way "
    "(null for fewer than 2 elevations), for debugging a mismatch.",
    "recompute_track_metrics: input {points, original_distance_m: double, "
    "original_moving_time: int, original_elapsed_time: int} (0.0/0/0 are the Python "
    "defaults, i.e. 'no originals') -> {distance (m), total_elevation_gain, elev_high, "
    "elev_low, start_latlng, end_latlng, average_speed, moving_time: int, elapsed_time: int}.",
    "apportion_gain: input {stored: double|null, before, after} -> double.",
    "sentinel_mask: input {elevations, distances_km} -> list of booleans, true where an "
    "exact 0.0 is the pre-#374 'no reading' sentinel (_sentinel_mask in "
    "alembic/versions/c4a9e1f70b38_repair_elevation_dropout_sentinel.py). Each maximal "
    "run of 0.0 is judged by its neighbour on each side that exists: step = |neighbour|, "
    "skipped when step < _SENTINEL_MIN_STEP_M; grade = step / (|distance between the "
    "neighbour and the run's nearest sample| * 1000), infinity when that distance is 0. "
    "The run is a dropout when the largest grade is strictly > _SENTINEL_MIN_GRADE; no "
    "grade (all-zero series, or steps too small) means real. Every sample false when "
    "the two lists differ in length. The repair then maps true samples to null and calls "
    "interpolate_elevation_gaps.",
    "Python semantics to mirror: (1) recompute_track_metrics times are int(round(x)) "
    "with Python's round, i.e. HALF TO EVEN (2.5 -> 2, 3.5 -> 4), unlike Dart's round; "
    "the polyline encoder alone rounds half away from zero. (2) a median is the element "
    "at index len // 2 of the sorted list (the upper middle for an even length). "
    "(3) noise_estimate differences pair element i with i + stride; it stops as soon as "
    "an order has fewer than _NOISE_MIN_DIFFERENCES differences (even below order 3), "
    "samples every step-th difference with step = 1 + len // _NOISE_MEDIAN_SAMPLE_CAP, "
    "and keeps the smallest sigma over orders 3..5, 0.0 if none. "
    "(4) _NOISE_DIFFERENCE_SCALE[k] = 1.4826 / sqrt(C(2k, k)). (5) smoothing widens its "
    "window while d[i] - d[lo] > half_km and while d[hi+1] - d[i] <= half_km; it is "
    "skipped (window 1.0) for fewer than 3 samples or distances null / of another "
    "length. (6) gain books a rise when value - ref >= threshold and follows a fall "
    "when ref - value >= threshold. (7) recompute_track_metrics accumulates distance "
    "over every point but records elevation (with its cumulative distance) only for "
    "points that have one; elev_high/low are null when none has.",
]


# ── Inputs ───────────────────────────────────────────────────────────────────

def _r(values: List[float], digits: int) -> List[float]:
    return [round(v, digits) for v in values]


def _series(track: gen.Track) -> Dict[str, List[float]]:
    """A bench track as exact-decimal ``{elevations, distances_km}``."""
    elevations, distances, _ = track
    return {"elevations": _r(elevations, 2), "distances_km": _r(distances, 6)}


def _walk(count: int, spacing_m: float, bearing_deg: float = 30.0,
          start=(45.83, 6.86)) -> List[List[float]]:
    """``count`` latlngs from ``start`` along a bearing, 5 decimals as decoded."""
    lat, lng = start
    out = []
    dy = spacing_m * math.cos(math.radians(bearing_deg)) / 111_320.0
    for _ in range(count):
        out.append([round(lat, 5), round(lng, 5)])
        dx = spacing_m * math.sin(math.radians(bearing_deg)) / (
            111_320.0 * math.cos(math.radians(lat)))
        lat += dy
        lng += dx
    return out


def _points(latlngs: List[List[float]], elevs: List[Optional[float]]) -> List[list]:
    return [[lat, lng, e] for (lat, lng), e in zip(latlngs, elevs)]


def _track_points(p: list) -> List[te.TrackPoint]:
    return [te.TrackPoint(lat=lat, lng=lng, elev=e) for lat, lng, e in p]


def _as_lists(points: List[te.TrackPoint]) -> List[list]:
    return [[p.lat, p.lng, p.elev] for p in points]


def _with_dropouts(elevations: List[float], runs) -> List[float]:
    """The pre-#374 stored form: runs of the ``0.0`` "no reading" sentinel."""
    out = list(elevations)
    for start, length in runs:
        for i in range(start, start + length):
            out[i] = 0.0
    return out


# ── Sections ─────────────────────────────────────────────────────────────────

def _haversine() -> List[dict]:
    cases = [
        ("same_point_is_zero", 45.83, 6.86, 45.83, 6.86),
        ("one_degree_of_latitude_on_a_meridian", 0.0, 0.0, 1.0, 0.0),
        ("one_degree_of_longitude_on_the_equator", 0.0, 0.0, 0.0, 1.0),
        ("one_degree_of_longitude_at_60_north", 60.0, 10.0, 60.0, 11.0),
        ("short_hop_of_about_100_m_in_the_alps", 45.83, 6.86, 45.8309, 6.86),
        ("across_the_antimeridian", 10.0, 179.5, 10.0, -179.5),
        ("southern_and_western_hemispheres", -33.8688, -70.6693, -34.6037, -58.3816),
        ("near_the_north_pole", 89.9, 0.0, 89.9, 180.0),
        ("antipodal_points_half_the_circumference", 0.0, 0.0, 0.0, 180.0),
    ]
    return [{"name": name, "input": {"lat1": a, "lng1": b, "lat2": c, "lng2": d},
             "expected": haversine_km(a, b, c, d)}
            for name, a, b, c, d in cases]


def _polyline() -> List[dict]:
    halves = [2.5e-5, -2.5e-5, 1.000005, 45.000025, -45.000025]
    for v in halves:  # the half-way cases must really be half-way
        assert math.modf(abs(v) * 100000)[0] == 0.5, v
    cases = [
        ("no_points_is_null", []),
        ("single_point", [[45.83, 6.86]]),
        ("google_reference_example",
         [[38.5, -120.2], [40.7, -120.95], [43.252, -126.453]]),
        ("negative_coordinates", [[-33.8688, -70.6693], [-34.6037, -58.3816]]),
        ("half_way_rounds_away_from_zero_positive", [[2.5e-5, 1.000005]]),
        ("half_way_rounds_away_from_zero_negative", [[-2.5e-5, -45.000025]]),
        ("half_way_in_deltas", [[45.000025, 1.000005], [-45.000025, -2.5e-5]]),
        ("antimeridian_crossing",
         [[10.0, 179.99999], [10.00001, -179.99999], [10.00002, -179.99998]]),
        ("coincident_points_zero_deltas", [[45.83, 6.86], [45.83, 6.86], [45.83, 6.86]]),
        ("pole_to_pole_large_delta", [[90.0, -180.0], [-90.0, 180.0]]),
        ("more_than_five_decimals_are_rounded", [[45.123456789, 6.987654321]]),
    ]
    out = []
    for name, pts in cases:
        tps = [te.TrackPoint(lat=lat, lng=lng) for lat, lng in pts]
        out.append({"name": name, "input": {"points": pts},
                    "expected": te.points_to_polyline(tps)})
    return out


def _align() -> List[dict]:
    latlngs = _walk(12, 25.0)
    line = te.points_to_polyline(_track_points(_points(latlngs, [None] * 12)))
    full = te.points_to_elevation_profile(_track_points(
        _points(latlngs, [1000.0 + 3.0 * i for i in range(12)])))
    dists, elevs = _r(full[0], 9), full[1]  # rounded: inputs stay exact decimals
    cases = [
        ("null_polyline_is_empty", None, None),
        ("empty_polyline_is_empty", "", None),
        ("no_profile_gives_null_elevations", line, None),
        ("empty_profile_lists_give_null_elevations",
         line, {"distances_km": [], "elevations_m": []}),
        ("profile_length_mismatch_gives_null_elevations",
         line, {"distances_km": dists[:5], "elevations_m": elevs[:4]}),
        ("profile_from_the_same_points_round_trips",
         line, {"distances_km": dists, "elevations_m": elevs}),
        ("sparse_profile_is_interpolated_by_distance",
         line, {"distances_km": [0.0, 0.1, 0.27], "elevations_m": [1000.0, 1040.0, 1010.0]}),
        ("track_past_the_profile_takes_its_last_sample",
         line, {"distances_km": [0.0, 0.05], "elevations_m": [500.0, 510.0]}),
        ("track_before_the_profile_takes_its_first_sample",
         line, {"distances_km": [0.08, 0.2], "elevations_m": [700.0, 650.0]}),
        ("implausible_profile_sample_makes_nearby_points_missing",
         line, {"distances_km": [0.0, 0.1, 0.2, 0.3],
                "elevations_m": [100.0, 65535.0, 120.0, 130.0]}),
        ("two_point_track",
         te.points_to_polyline(_track_points(_points(latlngs[:2], [None, None]))),
         {"distances_km": [0.0, 0.025], "elevations_m": [12.5, -3.25]}),
        ("coincident_points_share_one_elevation",
         te.points_to_polyline(_track_points(
             [[45.83, 6.86, None], [45.83, 6.86, None], [45.8302, 6.86, None]])),
         {"distances_km": [0.0, 0.01, 0.0222], "elevations_m": [200.0, 210.0, 230.0]}),
    ]
    out = []
    for name, poly, profile in cases:
        arg = None if profile is None else (profile["distances_km"], profile["elevations_m"])
        out.append({"name": name,
                    "input": {"summary_polyline": poly, "elevation_profile": profile},
                    "expected": _as_lists(te.align_points(poly, arg))})
    return out


def _profile_section() -> List[dict]:
    ll = _walk(8, 40.0)
    base = [400.0, 402.5, 405.0, 404.0, 410.0, 415.5, 413.0, 420.0]

    def holes(*idx):
        return [None if i in idx else e for i, e in enumerate(base)]

    cases = [
        ("no_points_is_null", []),
        ("all_missing_is_null", _points(ll, [None] * 8)),
        ("every_point_has_an_elevation", _points(ll, base)),
        ("interior_gap_is_interpolated", _points(ll, holes(2, 3, 5))),
        ("leading_gap_extends_the_first_reading", _points(ll, holes(0, 1))),
        ("trailing_gap_extends_the_last_reading", _points(ll, holes(6, 7))),
        ("single_reading_fills_everything", _points(ll, holes(0, 1, 2, 4, 5, 6, 7))),
        ("implausible_raw_elevations_are_missing",
         _points(ll, [400.0, 65535.0, 405.0, -25000.0, 410.0, 415.5, 413.0, 420.0])),
        ("two_points", _points(ll[:2], [10.0, 20.0])),
        ("coincident_points_zero_span_gap",
         [[45.83, 6.86, 100.0], [45.83, 6.86, None], [45.83, 6.86, 120.0],
          [45.8304, 6.86, 125.0]]),
    ]
    out = []
    for name, pts in cases:
        result = te.points_to_elevation_profile(_track_points(pts))
        out.append({"name": name, "input": {"points": pts},
                    "expected": None if result is None else
                    {"distances_km": result[0], "elevations_m": result[1]}})
    return out


def _interpolate() -> List[dict]:
    d = [0.0, 0.1, 0.25, 0.3, 0.5, 0.55, 0.9]
    climb = _series(gen.climb(300.0, 3.0, 10.0, "barometric"))
    sentinel = _with_dropouts(climb["elevations"], [(40, 3), (150, 1), (220, 6)])
    holed = [None if e == 0.0 else e for e in sentinel]
    cases = [
        ("no_holes_is_unchanged", d, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]),
        ("interior_holes_are_linear_by_distance",
         d, [100.0, None, None, 130.0, None, 90.0, 95.0]),
        ("leading_and_trailing_holes_extend_nearest",
         d, [None, None, 50.0, 60.0, 55.0, None, None]),
        ("single_known_value_fills_everything",
         d, [None, None, None, -12.5, None, None, None]),
        ("equal_bracketing_distances_take_the_left_value",
         [0.0, 0.1, 0.1, 0.1, 0.2], [10.0, 20.0, None, 30.0, 40.0]),
        ("sentinel_dropouts_mapped_to_holes_are_repaired",
         climb["distances_km"], holed),
        ("no_known_value_raises", d, [None] * 7),
    ]
    out = []
    for name, dist, elev in cases:
        case: Dict[str, Any] = {"name": name,
                                "input": {"distances_km": dist, "elevations": elev}}
        try:
            case["expected"] = te.interpolate_elevation_gaps(dist, elev)
        except ValueError:
            case["expected_error"] = "ValueError"
        out.append(case)
    return out


def _run_stride() -> List[dict]:
    held5 = _series(gen.held_readings(0.3, 2.0, hold=5, kind="barometric"))["elevations"]
    cases = [
        ("empty_is_one", []),
        ("single_sample_is_one", [5.0]),
        ("all_distinct_is_one", [1.0, 2.0, 3.0, 4.0, 5.0]),
        ("held_five_samples", held5),
        ("constant_series_caps_at_max_stride", [7.0] * 40),
        ("constant_series_below_cap", [7.0] * 9),
        ("half_runs_of_one_half_runs_of_two_is_strictly_more_than_half",
         [1.0, 2.0, 2.0, 3.0, 4.0, 4.0]),
        ("quantised_altitude_pairs_stay_at_one",
         [10.0, 10.0, 11.0, 12.0, 12.0, 13.0, 14.0, 15.0, 15.0, 16.0]),
    ]
    return [{"name": n, "input": {"elevations": e}, "expected": te._run_stride(e)}
            for n, e in cases]


def _noise_estimate() -> List[dict]:
    # 20004 samples: under a cap of 20000, orders 3, 4, 5 hold 20001, 20000 and
    # 19999 differences, so the sampling step changes across them; the seed is
    # one whose estimate moves when the cap is off by one either way, or ignored.
    long_white = _series(gen.flat(20.004, 1.0, "white", seed=28))["elevations"]
    assert len(long_white) == 20004
    cases = [
        ("too_short_for_any_order_is_zero", [1.0, 2.0, 4.0, 3.0, 5.0, 6.0, 2.0, 1.0]),
        ("one_short_of_order_three_is_zero", [float(i % 3) for i in range(10)]),
        ("just_enough_for_order_three", [float(i % 3) for i in range(11)]),
        ("clean_quadratic_has_no_noise", [0.01 * i * i for i in range(30)]),
        ("white_noise_three_metres",
         _series(gen.flat(0.6, 2.0, "white"))["elevations"]),
        ("held_readings_difference_at_the_stride",
         _series(gen.held_readings(1.0, 2.0, hold=5, kind="barometric"))["elevations"]),
        ("long_series_at_the_median_sample_cap_boundary", long_white),
    ]
    out = []
    for name, e in cases:
        sigma, stride = te._noise_estimate(e)
        out.append({"name": name, "input": {"elevations": e},
                    "expected": {"sigma": sigma, "stride": stride}})
    return out


def _smooth() -> List[dict]:
    dense = _series(gen.climb(40.0, 0.4, 2.0, "barometric"))
    mid = _series(gen.climb(40.0, 1.0, 10.0, "barometric"))
    sparse = _series(gen.flat(4.0, 40.0, "white", speed_ms=5.0))
    irregular_d = [0.0, 0.005, 0.007, 0.03, 0.031, 0.06, 0.1, 0.101, 0.102, 0.15]
    irregular_e = [10.0, 11.0, 10.5, 12.0, 13.0, 12.5, 15.0, 14.0, 16.0, 15.5]
    cases = [
        ("fewer_than_three_samples_unchanged", [1.0, 2.0], [0.0, 0.01], 0.5, 1),
        ("no_distances_unchanged", [1.0, 2.0, 3.0, 2.0], None, 0.5, 1),
        ("distance_length_mismatch_unchanged", [1.0, 2.0, 3.0, 2.0], [0.0, 0.1, 0.2], 0.5, 1),
        ("clean_dense_keeps_the_60_m_floor",
         dense["elevations"], dense["distances_km"], 0.0, 1),
        ("small_wanted_span_stays_at_the_floor",
         dense["elevations"], dense["distances_km"], 3.0, 2),
        ("noise_widens_between_floor_and_cap",
         mid["elevations"], mid["distances_km"], 3.0, 1),
        ("noise_widens_on_a_dense_track",
         dense["elevations"], dense["distances_km"], 7.0, 1),
        ("heavy_noise_on_sparse_track_hits_the_240_m_cap",
         sparse["elevations"], sparse["distances_km"], 3.0, 1),
        ("irregular_spacing", irregular_e, irregular_d, 1.0, 1),
    ]
    out = []
    for name, e, d, sigma, stride in cases:
        smoothed, window = te._smooth_elevations(e, d, sigma, stride)
        out.append({"name": name,
                    "input": {"elevations": e, "distances_km": d,
                              "sigma": sigma, "stride": stride},
                    "expected": {"smoothed": smoothed, "window": window}})
    return out


def _threshold() -> List[dict]:
    cases = [
        ("zero_noise_clamps_to_the_floor", 0.0, 1, 1.0),
        ("mid_noise_scales_by_the_multiple", 2.0, 1, 4.0),
        ("stride_divides_the_window", 2.0, 4, 4.0),
        ("window_below_stride_counts_as_one", 1.5, 5, 2.0),
        ("huge_noise_clamps_to_the_ceiling", 50.0, 1, 1.0),
    ]
    return [{"name": n, "input": {"sigma": s, "stride": k, "window": w},
             "expected": te._noise_threshold(s, k, w)} for n, s, k, w in cases]


def _gain() -> List[dict]:
    climb_baro = _series(gen.climb(200.0, 3.0, 3.0, "barometric"))
    sentinel_src = _series(gen.climb(300.0, 3.0, 10.0, "barometric"))
    sentinel = _with_dropouts(sentinel_src["elevations"], [(40, 3), (150, 1), (220, 6)])
    repaired = te.interpolate_elevation_gaps(
        sentinel_src["distances_km"], [None if e == 0.0 else e for e in sentinel])
    quantised = _series(gen.climb(80.0, 1.5, 3.0, "barometric"))
    quantised["elevations"] = [float(round(e)) for e in quantised["elevations"]]
    cases = [
        ("empty_is_zero", {"elevations": [], "distances_km": []}),
        ("single_sample_is_zero", {"elevations": [100.0], "distances_km": [0.0]}),
        ("two_samples_step_up", {"elevations": [100.0, 112.0], "distances_km": [0.0, 0.2]}),
        ("flat_constant", {"elevations": [250.0] * 50,
                           "distances_km": [round(i * 0.005, 6) for i in range(50)]}),
        ("flat_white_noise_dense", _series(gen.flat(1.5, 5.0, "white"))),
        ("flat_barometric", _series(gen.flat(2.0, 2.0, "barometric"))),
        ("flat_sparse_noisy_smart_recording",
         _series(gen.flat(6.0, 40.0, "white", speed_ms=5.0))),
        ("climb_barometric", climb_baro),
        ("climb_white_noise", _series(gen.climb(300.0, 4.0, 10.0, "white", speed_ms=5.0))),
        ("stepped_altimeter_held_5", _series(
            gen.held_readings(2.0, 2.0, hold=5, kind="barometric"))),
        ("stepped_altimeter_held_10", _series(
            gen.held_readings(2.0, 2.0, hold=10, kind="barometric"))),
        ("clean_planned_route_sparse_rollers",
         _series(gen.rollers(20.0, 600.0, 6.0, 100.0, "clean"))),
        ("rollers_barometric", _series(gen.rollers(10.0, 200.0, 2.0, 2.0, "barometric"))),
        ("rollers_triangular_barometric",
         _series(gen.rollers(10.0, 200.0, 2.0, 2.0, "barometric", shape="tri"))),
        ("rollers_phone_gps_tau_20",
         _series(gen.rollers(10.0, 200.0, 2.0, 2.0, "phone", speed_ms=2.0, tau_s=20.0))),
        ("fragment_of_a_climb", _series(gen.fragment(
            gen.climb(200.0, 3.0, 3.0, "barometric"),
            gen.climb(200.0, 3.0, 3.0, "clean"), 0.30, 0.45))),
        ("quantised_to_whole_metres", quantised),
        ("sentinel_dropouts_as_stored_before_374",
         {"elevations": sentinel, "distances_km": sentinel_src["distances_km"]}),
        ("sentinel_dropouts_after_repair",
         {"elevations": repaired, "distances_km": sentinel_src["distances_km"]}),
        ("no_distances_skips_smoothing",
         {"elevations": climb_baro["elevations"][:300], "distances_km": None}),
        ("distance_length_mismatch_skips_smoothing",
         {"elevations": climb_baro["elevations"][:300],
          "distances_km": climb_baro["distances_km"][:299]}),
        ("short_tail_below_min_differences",
         {"elevations": [300.0, 301.5, 303.0, 302.0, 305.0, 304.0],
          "distances_km": [0.0, 0.01, 0.02, 0.03, 0.04, 0.05]}),
    ]
    out = []
    for name, inp in cases:
        e, d = inp["elevations"], inp["distances_km"]
        diagnostics = None
        if len(e) >= 2:
            sigma, stride = te._noise_estimate(e)
            _, window = te._smooth_elevations(e, d, sigma, stride)
            diagnostics = {"sigma": sigma, "stride": stride, "window": window,
                           "threshold": te._noise_threshold(sigma, stride, window)}
        out.append({"name": name, "input": {"elevations": e, "distances_km": d},
                    "expected": te.elevation_gain(e, d),
                    "diagnostics": diagnostics})
    return out


def _recompute() -> List[dict]:
    climb = _series(gen.climb(150.0, 1.0, 5.0, "barometric"))
    ll = _walk(len(climb["elevations"]), 5.0)
    noisy = _points(ll, climb["elevations"])
    small_ll = _walk(6, 50.0)
    small = _points(small_ll, [500.0, 505.0, 503.0, 512.0, 520.0, 518.0])
    full_m = te.recompute_track_metrics(_track_points(small)).distance

    def holes(pts, *idx):
        return [[a, b, None if i in idx else e] for i, (a, b, e) in enumerate(pts)]

    cases = [
        ("no_points", [], 0.0, 0, 0),
        ("single_point_with_elevation", [[45.83, 6.86, 1200.0]], 0.0, 0, 0),
        ("single_point_without_elevation", [[45.83, 6.86, None]], 500.0, 100, 120),
        ("two_points", small[:2], 0.0, 0, 0),
        ("coincident_points", [[45.83, 6.86, 100.0]] * 3, 1000.0, 300, 400),
        ("no_originals_gives_zero_times", small, 0.0, 0, 0),
        ("trim_apportions_times_to_retained_distance", small, full_m * 3.7, 1234, 2000),
        ("extend_clamps_the_fraction_to_one", small, full_m / 2.0, 900, 1000),
        ("exact_half_rounds_half_to_even", small, full_m * 2.0, 5, 7),
        ("exact_half_rounds_half_to_even_larger", small, full_m * 2.0, 1001, 1003),
        ("interior_missing_elevations", holes(small, 2, 3), 0.0, 0, 0),
        ("leading_and_trailing_missing_elevations", holes(small, 0, 5), full_m, 600, 600),
        ("no_elevations_at_all", holes(small, 0, 1, 2, 3, 4, 5), full_m, 600, 650),
        ("implausible_elevations_are_dropped",
         [[a, b, 65535.0 if i == 2 else (-25000.0 if i == 4 else e)]
          for i, (a, b, e) in enumerate(small)], 0.0, 0, 0),
        ("noisy_climb_with_originals", noisy, 1500.0, 1800, 2400),
    ]
    out = []
    for name, pts, dist, moving, elapsed in cases:
        m = te.recompute_track_metrics(
            _track_points(pts), original_distance_m=dist,
            original_moving_time=moving, original_elapsed_time=elapsed)
        out.append({
            "name": name,
            "input": {"points": pts, "original_distance_m": dist,
                      "original_moving_time": moving, "original_elapsed_time": elapsed},
            "expected": {
                "distance": m.distance, "total_elevation_gain": m.total_elevation_gain,
                "elev_high": m.elev_high, "elev_low": m.elev_low,
                "start_latlng": m.start_latlng, "end_latlng": m.end_latlng,
                "average_speed": m.average_speed, "moving_time": m.moving_time,
                "elapsed_time": m.elapsed_time,
            },
        })
    return out


def _apportion() -> List[dict]:
    from src.project.repo_activities import _apportion_gain

    cases = [
        ("stored_none_falls_back_to_after", None, 120.0, 80.0),
        ("before_zero_falls_back_to_after", 500.0, 0.0, 30.0),
        ("before_negative_falls_back_to_after", 500.0, -1.0, 30.0),
        ("positive_before_scales_stored", 640.0, 410.0, 205.0),
        ("stored_zero_stays_zero", 0.0, 410.0, 205.0),
        ("after_zero_gives_zero", 640.0, 410.0, 0.0),
        ("after_larger_than_before_scales_up", 100.0, 50.0, 75.0),
    ]
    return [{"name": n, "input": {"stored": s, "before": b, "after": a},
             "expected": _apportion_gain(s, b, a)} for n, s, b, a in cases]


def _sentinel_migration():
    """The #374 dropout repair migration, loaded from its file as
    tests/test_migration_elevation_non_finite_repair.py loads its own: the
    revision id makes it no importable module name."""
    import importlib.util

    path = _ROOT / "alembic" / "versions" / "c4a9e1f70b38_repair_elevation_dropout_sentinel.py"
    spec = importlib.util.spec_from_file_location("dropout_sentinel_migration", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _sentinel_mask() -> List[dict]:
    mask = _sentinel_migration()._sentinel_mask
    d10 = [round(i * 0.01, 6) for i in range(8)]  # a sample every 10 m
    cases = [
        ("empty", [], []),
        ("no_zeros", [500.0, 501.0, 502.0, 503.0], d10[:4]),
        ("all_zero_has_no_neighbour_to_judge_by", [0.0] * 5, d10[:5]),
        ("interior_dropout_in_the_mountains",
         [500.0, 501.0, 0.0, 0.0, 0.0, 504.0, 505.0, 506.0], d10),
        ("single_sample_dropout", [500.0, 501.0, 502.0, 0.0, 504.0], d10[:5]),
        ("leading_dropout_run", [0.0, 0.0, 480.0, 481.0, 482.0], d10[:5]),
        ("trailing_dropout_run", [480.0, 481.0, 482.0, 0.0, 0.0], d10[:5]),
        ("dropout_at_30_m_near_sea_level_is_still_a_cliff",
         [30.0, 30.5, 0.0, 31.0, 31.5], d10[:5]),
        ("real_beach_at_0_m_approached_gently",
         [6.0, 4.0, 2.0, 0.0, 0.0, 0.0, 1.5, 3.0], d10),
        ("real_beach_below_a_steep_but_real_coastal_cliff",
         [60.0, 0.0, 0.0, 0.0], [0.0, 0.1, 0.2, 0.3]),
        ("step_below_5_m_is_never_judged", [4.5, 0.0, 4.9], [0.0, 0.001, 0.002]),
        ("grade_of_exactly_one_is_not_a_dropout",
         [10.0, 0.0, 10.0], [0.0, 0.01, 0.02]),
        ("one_steep_side_is_enough",
         [3.0, 0.0, 0.0, 300.0], [0.0, 0.05, 0.06, 0.07]),
        ("zero_distance_step_is_infinitely_steep",
         [100.0, 0.0, 101.0], [0.0, 0.0, 0.5]),
        ("below_sea_level_neighbour_counts_by_magnitude",
         [-30.0, 0.0, -31.0], [0.0, 0.01, 0.02]),
        ("two_separate_runs_judged_separately",
         [500.0, 0.0, 501.0, 2.0, 0.0, 1.0, 0.0, 600.0], d10),
        ("distance_length_mismatch_marks_nothing",
         [500.0, 0.0, 501.0], [0.0, 0.01]),
    ]
    return [{"name": n, "input": {"elevations": e, "distances_km": d},
             "expected": mask(e, d)} for n, e, d in cases]


def python_constants() -> Dict[str, Any]:
    """The constants the Dart port must declare, by their Python names."""
    return {
        "ELEV_SMOOTH_SPAN_M": te.ELEV_SMOOTH_SPAN_M,
        "ELEV_SMOOTH_MAX_SPAN_M": te.ELEV_SMOOTH_MAX_SPAN_M,
        "ELEV_SMOOTH_TARGET_SIGMA_M": te.ELEV_SMOOTH_TARGET_SIGMA_M,
        "ELEV_NOISE_SIGMA_MULTIPLE": te.ELEV_NOISE_SIGMA_MULTIPLE,
        "ELEV_GAIN_THRESHOLD_MIN_M": te.ELEV_GAIN_THRESHOLD_MIN_M,
        "ELEV_GAIN_THRESHOLD_MAX_M": te.ELEV_GAIN_THRESHOLD_MAX_M,
        "_NOISE_DIFFERENCE_ORDERS": list(te._NOISE_DIFFERENCE_ORDERS),
        "_NOISE_MIN_DIFFERENCES": te._NOISE_MIN_DIFFERENCES,
        "_NOISE_MAX_RUN_STRIDE": te._NOISE_MAX_RUN_STRIDE,
        "_NOISE_MEDIAN_SAMPLE_CAP": te._NOISE_MEDIAN_SAMPLE_CAP,
    }


_SECTIONS: Dict[str, Callable[[], List[dict]]] = {
    "haversine_km": _haversine,
    "polyline_encode": _polyline,
    "align_points": _align,
    "points_to_elevation_profile": _profile_section,
    "interpolate_elevation_gaps": _interpolate,
    "run_stride": _run_stride,
    "noise_estimate": _noise_estimate,
    "smooth_elevations": _smooth,
    "noise_threshold": _threshold,
    "elevation_gain": _gain,
    "recompute_track_metrics": _recompute,
    "apportion_gain": _apportion,
    "sentinel_mask": _sentinel_mask,
}


def build_vectors() -> Dict[str, Any]:
    """Every vector, as plain JSON types."""
    constants = python_constants()
    # Derived, written so a mismatch in the port's formula shows on its own.
    constants["_NOISE_DIFFERENCE_SCALE"] = {
        str(k): v for k, v in te._NOISE_DIFFERENCE_SCALE.items()}
    # The dropout rule's, from the migration; not in elevation_gain.dart.
    migration = _sentinel_migration()
    constants["_SENTINEL_MIN_GRADE"] = migration._SENTINEL_MIN_GRADE
    constants["_SENTINEL_MIN_STEP_M"] = migration._SENTINEL_MIN_STEP_M
    data: Dict[str, Any] = {"_schema": _SCHEMA, "constants": constants}
    for section, build in _SECTIONS.items():
        cases = build()
        names = [c["name"] for c in cases]
        assert len(names) == len(set(names)), f"duplicate case name in {section}"
        data[section] = cases
    return data


def _is_leaf(value: Any) -> bool:
    """A scalar, or a list of numbers, nulls and such lists (one line each).
    A list of strings (the schema notes) is not: one string per line."""
    if isinstance(value, list):
        return all(_is_leaf(v) and not isinstance(v, (dict, str)) for v in value)
    return not isinstance(value, dict)


def render(value: Any, indent: int = 0) -> str:
    """JSON, sorted keys, one line per leaf list so long series stay compact."""
    pad = "  " * (indent + 1)
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = [f"{pad}{json.dumps(k)}: {render(value[k], indent + 1)}"
                 for k in sorted(value)]
        return "{\n" + ",\n".join(items) + "\n" + "  " * indent + "}"
    if isinstance(value, list) and not _is_leaf(value):
        items = [pad + render(v, indent + 1) for v in value]
        return "[\n" + ",\n".join(items) + "\n" + "  " * indent + "]"
    return json.dumps(value, separators=(",", ":"), allow_nan=False)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(build_vectors()) + "\n")
    print(f"wrote {os.path.relpath(OUTPUT, _ROOT)}")


if __name__ == "__main__":
    main()
